# Generated by Django 3.2.9 on 2021-12-11 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desaparecido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des_cedula', models.DecimalField(decimal_places=2, max_digits=9, max_length=20)),
                ('des_nombre', models.CharField(max_length=100)),
                ('des_apellido', models.CharField(max_length=100)),
                ('des_edad', models.IntegerField()),
                ('des_fecha_desaparecido', models.DateField()),
                ('des_foto', models.CharField(max_length=1000)),
                ('des_tipo_sangre', models.CharField(max_length=5)),
                ('des_sexo', models.CharField(max_length=2)),
                ('des_color_piel', models.CharField(max_length=20)),
                ('des_ciudad_recidencia', models.CharField(max_length=50)),
                ('des_estatura', models.FloatField(max_length=20)),
                ('des_estado_caso', models.BooleanField(default=True)),
                ('fam_nombre', models.CharField(max_length=100)),
                ('fam_apellido', models.CharField(max_length=100)),
                ('fam_telefono', models.DecimalField(decimal_places=2, max_digits=9, max_length=20)),
                ('fam_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes_Encontrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_notifica_cedula', models.IntegerField()),
                ('p_notifica_nombres', models.CharField(max_length=50)),
                ('p_notifica_apellidos', models.CharField(max_length=50)),
                ('p_notifica_telefono', models.IntegerField()),
                ('p_notifica_lugar_encontrado', models.CharField(max_length=100)),
                ('p_notifica_direccion', models.CharField(max_length=100)),
                ('p_notifica_tipo_sangre', models.CharField(max_length=50)),
                ('p_id_desaparecido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desaparecido_reportes_encontrada', to='hackcodev.desaparecido')),
            ],
        ),
        migrations.CreateModel(
            name='Caso_Cerrado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cc_motivo_desaparicion', models.CharField(max_length=100)),
                ('cc_fecha_aparicion', models.DateField()),
                ('desaparecido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caso_cerrado', to='hackcodev.desaparecido')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('us_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('us_apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('us_entidad', models.CharField(max_length=100, verbose_name='Entidad')),
                ('us_telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('us_ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('us_direccion', models.EmailField(max_length=256, verbose_name='Direccion')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
