# Generated by Django 3.2.9 on 2021-12-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportesEncontrada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('p_notifica_cedula', models.IntegerField()),
                ('p_notifica_nombres', models.CharField(max_length=50)),
                ('p_notifica_apellidos', models.CharField(max_length=50)),
                ('p_notifica_telefono', models.IntegerField()),
                ('p_notifica_lugar_encontrado', models.CharField(max_length=100)),
                ('p_notifica_direccion', models.CharField(max_length=100)),
                ('p_notifica_tipo_sangre', models.CharField(max_length=50)),
            ],
        ),
    ]
