# Generated by Django 3.2.9 on 2021-12-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackcodev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='us_direccion',
            field=models.CharField(max_length=256, verbose_name='Direccion'),
        ),
    ]
